### ISSUE TITLE
Manual language update

### ISSUE THREAD

**Issue by EvelRus** [Return-To-The-Roots/languages#26]
Good afternoon
Please tell me how to add your translation to the game file directly? If I simply copy the file into the directory with languages, then when the game starts it is automatically replaced with the original one (And language pack updates have not been included in releases since August (

**Comment by Flamefire** [comment]
The update has just been done: https://github.com/Return-To-The-Roots/s25client/pull/1642

The replacement happens due to the auto-updater. So just start `s25client` directly not the `rttr.sh/bat` script to skip updating
